# Generated by Django 3.1.1 on 2020-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='', verbose_name='input file')),
                ('result_graph', models.ImageField(upload_to='', verbose_name='result graph')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'data set',
                'verbose_name_plural': 'data sets',
            },
        ),
    ]
