# Generated by Django 3.1.1 on 2020-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benfords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
